"""fix backpopulate name error

Revision ID: 31d84291c535
Revises: 2ffd03dcea4e
Create Date: 2025-04-11 13:24:53.640675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31d84291c535'
down_revision: Union[str, None] = '2ffd03dcea4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('listing_id', sa.UUID(), nullable=False))
    op.drop_constraint('reviews_product_id_fkey', 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'listings', ['listing_id'], ['id'])
    op.drop_column('reviews', 'product_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key('reviews_product_id_fkey', 'reviews', 'listings', ['product_id'], ['id'])
    op.drop_column('reviews', 'listing_id')
    # ### end Alembic commands ###
